In [1]:
import pandas as pd

In [3]:
data=pd.read_csv("D:\\DRUG\\drug.target.interaction.tsv",sep='\t')

In [4]:
data.head()

,DRUG_NAME,STRUCT_ID,TARGET_NAME,TARGET_CLASS,ACCESSION,GENE,SWISSPROT,ACT_VALUE,ACT_UNIT,ACT_TYPE,ACT_COMMENT,ACT_SOURCE,RELATION,MOA,MOA_SOURCE,ACT_SOURCE_URL,MOA_SOURCE_URL,ACTION_TYPE,TDL,ORGANISM
0,levobupivacaine,4,Potassium voltage-gated channel subfamily H me...,Ion channel,Q12809,KCNH2,KCNH2_HUMAN,4.890,NaN,IC50,Inhibition of wild-type human ERG channel expr...,CHEMBL,=,NaN,NaN,NaN,NaN,NaN,Tclin,Homo sapiens
1,levobupivacaine,4,Sodium channel protein type 1 subunit alpha,Ion channel,P35498,SCN1A,SCN1A_HUMAN,5.790,NaN,IC50,NaN,WOMBAT-PK,=,NaN,NaN,NaN,NaN,NaN,Tclin,Homo sapiens
2,levobupivacaine,4,Sodium channel protein type 4 subunit alpha,Ion channel,P35499,SCN4A,SCN4A_HUMAN,NaN,NaN,NaN,NaN,WOMBAT-PK,NaN,1.0,CHEMBL,NaN,https://www.ebi.ac.uk/chembl/compound/inspect/...,BLOCKER,Tclin,Homo sapiens
3,levobupivacaine,4,Prostaglandin E2 receptor EP1 subtype,GPCR,P34995,PTGER1,PE2R1_HUMAN,NaN,NaN,NaN,NaN,WOMBAT-PK,NaN,NaN,NaN,NaN,NaN,NaN,Tclin,Homo sapiens
4,levobupivacaine,4,Cytochrome P450 2D6,Enzyme,P10635,CYP2D6,CP2D6_HUMAN,6.707,NaN,IC50,"DRUGMATRIX: CYP450, 2D6 enzyme inhibition (sub...",DRUG MATRIX,=,NaN,NaN,NaN,NaN,NaN,Tclin,Homo sapiens

In [10]:
data=data[['DRUG_NAME','TARGET_NAME']]

In [11]:
data.head()

         DRUG_NAME                                        TARGET_NAME
0  levobupivacaine  Potassium voltage-gated channel subfamily H me...
1  levobupivacaine        Sodium channel protein type 1 subunit alpha
2  levobupivacaine        Sodium channel protein type 4 subunit alpha
3  levobupivacaine              Prostaglandin E2 receptor EP1 subtype
4  levobupivacaine                                Cytochrome P450 2D6

In [12]:
df=pd.read_csv("D:\\DRUG\\drug_names.tsv",sep='\t')
df.head(10)

            CID                 DRUG_NAME
0  CID100000085                 carnitine
1  CID100000119        gamma-aminobutyric
2  CID100000137          5-aminolevulinic
3  CID100000143                leucovorin
4  CID100000146  5-methyltetrahydrofolate
5  CID100000158                      PGE2
6  CID100000159              prostacyclin
7  CID100000160             prostaglandin
8  CID100000175                   acetate
9  CID100000187             acetylcholine

In [13]:
df_final= pd.merge(data,df,on='DRUG_NAME')

In [14]:
df_final.head()

     DRUG_NAME                             TARGET_NAME           CID
0     abacavir                     Gag-Pol polyprotein  CID100001971
1     abacavir            Reverse transcriptase/RNaseH  CID100001971
2     abacavir                   Reverse transcriptase  CID100001971
3  acamprosate  GABA-A receptor alpha-1/beta-3/gamma-2  CID100071158
4  acamprosate               Glutamate [NMDA] receptor  CID100071158

In [15]:
dxf=pd.read_csv("D:\\DRUG\\meddra_all_se.tsv",sep='\t')

In [16]:
dxf.head()

            CID          CID2       ATC   ST      ATC2            SIDE_EFFECT
0  CID100000085  CID000010917  C0000729  LLT  C0000729       Abdominal cramps
1  CID100000085  CID000010917  C0000729   PT  C0000737         Abdominal pain
2  CID100000085  CID000010917  C0000737  LLT  C0000737         Abdominal pain
3  CID100000085  CID000010917  C0000737   PT  C0687713  Gastrointestinal pain
4  CID100000085  CID000010917  C0000737   PT  C0000737         Abdominal pain

In [17]:
dff=pd.read_csv("D:\\DRUG\\meddra_all_se.tsv",sep='\t')
dff=dff.drop(columns=['ST','CID2','ATC','ATC2'])

In [18]:
dff.head(10)

            CID            SIDE_EFFECT
0  CID100000085       Abdominal cramps
1  CID100000085         Abdominal pain
2  CID100000085         Abdominal pain
3  CID100000085  Gastrointestinal pain
4  CID100000085         Abdominal pain
5  CID100000085              Amblyopia
6  CID100000085              Amblyopia
7  CID100000085                Anaemia
8  CID100000085                Anaemia
9  CID100000085               Anorexia

In [19]:
df2=pd.merge(df_final,dff,on='CID')

In [20]:
df2.head()

  DRUG_NAME          TARGET_NAME           CID            SIDE_EFFECT
0  abacavir  Gag-Pol polyprotein  CID100001971         Abdominal pain
1  abacavir  Gag-Pol polyprotein  CID100001971  Gastrointestinal pain
2  abacavir  Gag-Pol polyprotein  CID100001971         Abdominal pain
3  abacavir  Gag-Pol polyprotein  CID100001971        Lactic acidosis
4  abacavir  Gag-Pol polyprotein  CID100001971        Lactic acidosis

In [11]:
df_test=df2[df2['TARGET_NAME'].str.contains('Adenosine')]

In [12]:
df_test=df_test.drop_duplicates()

In [13]:
df_test=df_test[['DRUG_NAME','TARGET_NAME','SIDE_EFFECT']]
df_test

,DRUG_NAME,TARGET_NAME,SIDE_EFFECT
14602,adenosine,Adenosine receptor A2a,Anaphylactic shock
14604,adenosine,Adenosine receptor A2a,Angioedema
14606,adenosine,Adenosine receptor A2a,Apnoea
14608,adenosine,Adenosine receptor A2a,Arrhythmia
14610,adenosine,Adenosine receptor A2a,Asthenia
...,...,...,...
3486333,cisplatin,Adenosine receptor A3,Thrombotic microangiopathy
3486335,cisplatin,Adenosine receptor A3,Metastatic neoplasm
3486337,cisplatin,Adenosine receptor A3,Posterior reversible encephalopathy syndrome
3486339,cisplatin,Adenosine receptor A3,Vestibular toxicity
3486341,cisplatin,Adenosine receptor A3,Visual impairment

In [14]:
df_test.to_csv('drug_side_test.tsv', sep="\t",index=False)

In [15]:
df_test['number_of_side_effect']=1

In [16]:
dffff=df_test.groupby(by=["DRUG_NAME","TARGET_NAME"]).sum()

In [17]:
dffff

                                     number_of_side_effect
DRUG_NAME    TARGET_NAME
adenosine    Adenosine A2 receptor                     111
             Adenosine deaminase                       111
             Adenosine kinase                          222
             Adenosine receptor A1                     222
             Adenosine receptor A2a                    222
...                                                    ...
theophylline Adenosine receptor A2a                    172
             Adenosine receptor A2b                    172
             Adenosine receptor A3                     172
troglitazone Adenosine receptor A3                      31
zafirlukast  Adenosine receptor A3                      76

[95 rows x 1 columns]

In [18]:
dffff=df_test.groupby(by=["DRUG_NAME","TARGET_NAME"]).sum()

In [19]:
dffff

                                     number_of_side_effect
DRUG_NAME    TARGET_NAME
adenosine    Adenosine A2 receptor                     111
             Adenosine deaminase                       111
             Adenosine kinase                          222
             Adenosine receptor A1                     222
             Adenosine receptor A2a                    222
...                                                    ...
theophylline Adenosine receptor A2a                    172
             Adenosine receptor A2b                    172
             Adenosine receptor A3                     172
troglitazone Adenosine receptor A3                      31
zafirlukast  Adenosine receptor A3                      76

[95 rows x 1 columns]

In [20]:

dffff.nlargest(7, ['number_of_side_effect'])

                                    number_of_side_effect
DRUG_NAME   TARGET_NAME
nifedipine  Adenosine receptor A1                     548
            Adenosine receptor A2a                    548
gabapentin  Adenosine receptor A1                     523
ribavirin   Adenosine kinase                          453
            Adenosine receptor A1                     453
pentostatin Adenosine deaminase                       358
celecoxib   Adenosine receptor A3                     346

In [27]:
dfvx= pd.read_csv("D:\\DRUG\\Drug_CNN\\data_for_gnn.tsv",sep='\t')
dfvx.head()

                                              smiles  interact_with_adenosine
0                   BrC1=C(NC2=NCCN2)C=CC2=NC=CN=C12                        0
1   C#CC1=CC=CC(NC2=NC=NC3=C2C=C2OCCOCCOCCOC2=C3)=C1                        0
2                         C#CCN[C@@H]1CCC2=C1C=CC=C2                        0
3  CC(C)(C)C1=CC=C(C=C1)C(=O)CCCN1CCC(CC1)OC(C1=C...                        1
4                     C(C1=NCCN1)C1=CC=CC2=CC=CC=C12                        0